# Generated by Django 6.0 on 2025-12-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon_type',
            field=models.CharField(blank=True, choices=[('mild', 'Mild'), ('spicy', 'Spicy'), ('fresh', 'Fresh'), ('premium', 'Premium')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
